### PR TITLE
MAYH-8257 Use latest kafka libraries

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
👍 although this doesn't save you from skipping

**Comment by newhoggy** [comment]
Just keeping stuff up to date is all.  Jump guard is already in.

**Comment by AlexeyRaga** [comment]
Not so up to date, `2.4.1` is a bleeding edge! ;_

**Comment by newhoggy** [comment]
Updated!

**Comment by AlexeyRaga** [comment]
Still 👍 
Nothing you can do will change my mind.

**Pull request merged**
